/******************************************************************************************************************************************************************************************************\
***
*** Description       : TEMPLATE FILE USED FROM CFG GENERATOR:
*** Codefile          : ukfCfgTemplate.h
*** Documentation     :
*** Generated by : ukfCfgGen.m
*** Generation Time/Date : 16-Dec-2019 20:42:52
***
*** GNU General Public License v3
***
*** Copyright (c) 2019 ivo-georgiev
***
*** This program is free software: you can redistribute it and/or modify
*** it under the terms of the GNU General Public License as published by
*** the Free Software Foundation, either version 3 of the License, or
*** (at your option) any later version.
***
*** This program is distributed in the hope that it will be useful,
*** but WITHOUT ANY WARRANTY; without even the implied warranty of
*** MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*** GNU General Public License for more details.
***
*** You should have received a copy of the GNU General Public License
*** along with this program.  If not, see <https://www.gnu.org/licenses/>.
\******************************************************************************************************************************************************************************************************/
#ifndef UKFCFG2_H
#define UKFCFG2_H

#include "ukfLib.h"

extern UkfMatrix_t UkfMatrixCfg2;

#endif /* UKFCFG2_H */

